create table public.app_event_labels (
  sort_int bigint generated by default as identity not null,
  code text not null,
  name text not null,
  description text null,
  id uuid not null default gen_random_uuid (),
  constraint app_event_labels_pkey1 primary key (id),
  constraint app_event_labels_code_key1 unique (code),
  constraint app_event_labels_name_key unique (name)
) TABLESPACE pg_default;

create trigger log_app_event_labels_events
after INSERT
or DELETE
or
update on app_event_labels for EACH row
execute FUNCTION log_all_events ();