create table public.app_profiles (
  id uuid not null default gen_random_uuid (),
  name text not null,
  description text null,
  external_url text null,
  avatar_url text null,
  updated_at timestamp with time zone null,
  email text null,
  phone text null,
  created_at timestamp with time zone null default now(),
  notes text null,
  sort_int bigint generated by default as identity not null,
  auth_user_id uuid null,
  task_header_id uuid null,
  survey_header_id uuid null,
  deleted_by_id uuid null,
  deleted_at timestamp with time zone null,
  constraint app_profiles_pkey primary key (id, sort_int),
  constraint app_profiles_auth_user_id_key unique (auth_user_id),
  constraint app_profiles_id_key unique (id),
  constraint app_profiles_name_key unique (name),
  constraint app_profiles_task_header_id_key unique (task_header_id),
  constraint app_profiles_survey_header_id_key unique (survey_header_id),
  constraint app_profiles_survey_header_id_fkey foreign KEY (survey_header_id) references survey_headers (id) on update CASCADE on delete CASCADE,
  constraint app_profiles_auth_user_id_fkey foreign KEY (auth_user_id) references profiles (id) on update CASCADE on delete RESTRICT,
  constraint app_profiles_task_header_id_fkey foreign KEY (task_header_id) references task_headers (id) on update CASCADE on delete CASCADE,
  constraint app_profiles_deleted_by_id_fkey foreign KEY (deleted_by_id) references app_profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create trigger log_profiles_events
after INSERT
or DELETE
or
update on app_profiles for EACH row
execute FUNCTION log_all_events ();