create table public.approfile_relations (
  sort_int bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  id uuid not null default gen_random_uuid (),
  approfile_is uuid not null,
  relationship text not null,
  of_approfile uuid not null,
  assigned_by_person uuid null,
  assigned_by_automation uuid null,
  deleted_at timestamp with time zone null,
  deleted_by uuid null,
  is_deleted boolean null default false,
  constraint approfile_relations_pkey primary key (sort_int, id),
  constraint unique_approfile_relationship unique (approfile_is, relationship, of_approfile),
  constraint approfile_relations_id_key unique (id),
  constraint approfile_relations_deleted_by_fkey foreign KEY (deleted_by) references app_profiles (id),
  constraint approfile_relations_approfile_is_fkey foreign KEY (approfile_is) references app_profiles (id) on update CASCADE on delete CASCADE,
  constraint approfile_relations_of_approfile_fkey foreign KEY (of_approfile) references app_profiles (id) on update CASCADE on delete CASCADE,
  constraint approfile_relations_assigned_by_automation_fkey foreign KEY (assigned_by_automation) references automations (id) on update CASCADE on delete CASCADE,
  constraint approfile_relations_relationship_fkey foreign KEY (relationship) references relationships (name) on update CASCADE on delete CASCADE,
  constraint approfile_relations_assigned_by_person_fkey foreign KEY (assigned_by_person) references app_profiles (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create trigger log_app_event_approfile_relations
after INSERT
or DELETE
or
update on approfile_relations for EACH row
execute FUNCTION log_all_events ();

create trigger log_approfile_relations
after INSERT
or DELETE
or
update on approfile_relations for EACH row
execute FUNCTION log_all_events ();