create table public.notes_categories (
  id integer generated by default as identity not null,
  author_id uuid not null,
  category_name text not null,
  description text null,
  constraint notes_categories_pkey primary key (id),
  constraint notes_categories_category_name_key unique (category_name)
) TABLESPACE pg_default;