create table public.notes (
  sort_int integer generated by default as identity not null,
  id uuid not null default gen_random_uuid (),
  author_id uuid not null,
  audience_id uuid null,
  reply_to_id uuid null,
  title text null,
  content text null,
  status integer null,
  last_updated timestamp without time zone null default CURRENT_TIMESTAMP,
  created_at timestamp without time zone null default CURRENT_TIMESTAMP,
  constraint notes_pkey primary key (sort_int, id),
  constraint notes_id_key unique (sort_int),
  constraint notes_uuid_key unique (id),
  constraint notes_status_fkey foreign KEY (status) references notes_status (id)
) TABLESPACE pg_default;