create table public.notes_categorised (
  id bigint generated by default as identity not null,
  note_id uuid not null,
  note_category_id integer not null,
  created_at timestamp with time zone not null default now(),
  constraint notes_categorised_pkey primary key (id),
  constraint unique_note_tag_pair unique (note_id, note_category_id),
  constraint notes_categorised_note_category_id_fkey foreign KEY (note_category_id) references notes_categories (id) on update CASCADE on delete CASCADE,
  constraint notes_categorised_note_id_fkey foreign KEY (note_id) references notes (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;