create table public.task_assignments (
  id uuid not null default extensions.uuid_generate_v4 (),
  task_header_id uuid null,
  student_id uuid not null,
  manager_id uuid null,
  assigned_at timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
  completed_at timestamp with time zone null,
  abandoned_at timestamp with time zone null,
  step_id uuid null,
  sort_int integer generated by default as identity not null,
  assigned_by_person uuid null,
  assigned_by_automation uuid null,
  survey_header_id uuid null,
  survey_question_id uuid null,
  survey_answer_id uuid null,
  deleted_at timestamp with time zone null,
  deleted_by uuid null,
  is_deleted boolean null default false,
  constraint task_assignments_pkey primary key (id),
  constraint task_assignments_assigned_by_automation_fkey foreign KEY (assigned_by_automation) references automations (id) on update CASCADE on delete CASCADE,
  constraint task_assignments_assigned_by_person_fkey foreign KEY (assigned_by_person) references app_profiles (id) on update CASCADE on delete CASCADE,
  constraint task_assignments_deleted_by_fkey foreign KEY (deleted_by) references app_profiles (id),
  constraint task_assignments_manager_id_fkey foreign KEY (manager_id) references app_profiles (id) on update CASCADE on delete CASCADE,
  constraint task_assignments_step_id_fkey foreign KEY (step_id) references task_steps (id) on update CASCADE on delete CASCADE,
  constraint task_assignments_student_id_fkey foreign KEY (student_id) references app_profiles (id) on update CASCADE on delete CASCADE,
  constraint task_assignments_survey_answer_id_fkey foreign KEY (survey_answer_id) references survey_answers (id) on update CASCADE on delete CASCADE,
  constraint task_assignments_survey_header_id_fkey foreign KEY (survey_header_id) references survey_headers (id) on update CASCADE on delete CASCADE,
  constraint task_assignments_survey_question_id_fkey foreign KEY (survey_question_id) references survey_questions (id) on update CASCADE on delete CASCADE,
  constraint task_assignments_task_header_id_fkey foreign KEY (task_header_id) references task_headers (id) on delete CASCADE,
  constraint student_not_manager check ((student_id <> manager_id))
) TABLESPACE pg_default;

create index IF not exists idx_task_assignments_task on public.task_assignments using btree (task_header_id) TABLESPACE pg_default;

create index IF not exists idx_task_assignments_student on public.task_assignments using btree (student_id) TABLESPACE pg_default;

create index IF not exists idx_task_assignments_manager on public.task_assignments using btree (manager_id) TABLESPACE pg_default;

create trigger log_assignments_events
after INSERT
or DELETE
or
update on task_assignments for EACH row
execute FUNCTION log_all_events ();