SELECT
    t.tgname AS trigger_name,
    c.relname AS table_name,
    pg_get_triggerdef(t.oid) AS definition
FROM pg_trigger AS t
JOIN pg_class AS c ON t.tgrelid = c.oid
WHERE NOT t.tgisinternal;

--many of these are system not my triggers

| trigger_name                              | table_name          | definition                                                                                                                                                                                                             |
| ----------------------------------------- | ------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| enforce_bucket_name_length_trigger        | buckets             | CREATE TRIGGER enforce_bucket_name_length_trigger BEFORE INSERT OR UPDATE OF name ON storage.buckets FOR EACH ROW EXECUTE FUNCTION storage.enforce_bucket_name_length()                                                |
| new_task_header_create_appro              | task_headers        | CREATE TRIGGER new_task_header_create_appro AFTER INSERT ON public.task_headers FOR EACH ROW EXECUTE FUNCTION new_task_header_create_appro()                                                                           |
| update_objects_updated_at                 | objects             | CREATE TRIGGER update_objects_updated_at BEFORE UPDATE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.update_updated_at_column()                                                                             |
| tr_check_filters                          | subscription        | CREATE TRIGGER tr_check_filters BEFORE INSERT OR UPDATE ON realtime.subscription FOR EACH ROW EXECUTE FUNCTION realtime.subscription_check_filters()                                                                   |
| junk_cals-empty_function                  | profiles            | CREATE TRIGGER "junk_cals-empty_function" AFTER INSERT ON public.profiles FOR EACH ROW EXECUTE FUNCTION new_auth_user_create_appro()                                                                                   |
| log_assignments_events                    | task_assignments    | CREATE TRIGGER log_assignments_events AFTER INSERT OR DELETE OR UPDATE ON public.task_assignments FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                       |
| log_task_events                           | task_headers        | CREATE TRIGGER log_task_events AFTER INSERT OR DELETE OR UPDATE ON public.task_headers FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                                  |
| log_profiles_events                       | app_profiles        | CREATE TRIGGER log_profiles_events AFTER INSERT OR DELETE OR UPDATE ON public.app_profiles FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                              |
| log_task_steps_events                     | task_steps          | CREATE TRIGGER log_task_steps_events AFTER INSERT OR DELETE OR UPDATE ON public.task_steps FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                              |
| log_app_event_labels_events               | app_event_labels    | CREATE TRIGGER log_app_event_labels_events AFTER INSERT OR DELETE OR UPDATE ON public.app_event_labels FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                  |
| log_approfile_relations                   | approfile_relations | CREATE TRIGGER log_approfile_relations AFTER INSERT OR DELETE OR UPDATE ON public.approfile_relations FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                   |
| objects_insert_create_prefix              | objects             | CREATE TRIGGER objects_insert_create_prefix BEFORE INSERT ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.objects_insert_prefix_trigger()                                                                     |
| new_task_headers_create_steps             | task_headers        | CREATE TRIGGER new_task_headers_create_steps AFTER INSERT ON public.task_headers FOR EACH ROW EXECUTE FUNCTION new_task_headers_create_steps()                                                                         |
| objects_delete_delete_prefix              | objects             | CREATE TRIGGER objects_delete_delete_prefix AFTER DELETE ON storage.objects FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger()                                                                    |
| update_permissions_modtime                | permissions         | CREATE TRIGGER update_permissions_modtime BEFORE UPDATE ON extensions.permissions FOR EACH ROW EXECUTE FUNCTION update_modified_column()                                                                               |
| update_roles_modtime                      | roles               | CREATE TRIGGER update_roles_modtime BEFORE UPDATE ON extensions.roles FOR EACH ROW EXECUTE FUNCTION update_modified_column()                                                                                           |
| prefixes_create_hierarchy                 | prefixes            | CREATE TRIGGER prefixes_create_hierarchy BEFORE INSERT ON storage.prefixes FOR EACH ROW WHEN ((pg_trigger_depth() < 1)) EXECUTE FUNCTION storage.prefixes_insert_trigger()                                             |
| objects_update_create_prefix              | objects             | CREATE TRIGGER objects_update_create_prefix BEFORE UPDATE ON storage.objects FOR EACH ROW WHEN (((new.name <> old.name) OR (new.bucket_id <> old.bucket_id))) EXECUTE FUNCTION storage.objects_update_prefix_trigger() |
| prefixes_delete_hierarchy                 | prefixes            | CREATE TRIGGER prefixes_delete_hierarchy AFTER DELETE ON storage.prefixes FOR EACH ROW EXECUTE FUNCTION storage.delete_prefix_hierarchy_trigger()                                                                      |
| log_app_event_survey_headers              | survey_headers      | CREATE TRIGGER log_app_event_survey_headers AFTER INSERT OR DELETE OR UPDATE ON public.survey_headers FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                   |
| log_app_event_survey_questions            | survey_questions    | CREATE TRIGGER log_app_event_survey_questions AFTER INSERT OR DELETE OR UPDATE ON public.survey_questions FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                               |
| log_app_event_survey_answers              | survey_answers      | CREATE TRIGGER log_app_event_survey_answers AFTER INSERT OR DELETE OR UPDATE ON public.survey_answers FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                   |
| log_app_event_automations                 | automations         | CREATE TRIGGER log_app_event_automations AFTER INSERT OR DELETE OR UPDATE ON public.automations FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                         |
| log_app_event_approfile_relations         | approfile_relations | CREATE TRIGGER log_app_event_approfile_relations AFTER INSERT OR DELETE OR UPDATE ON public.approfile_relations FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                         |
| log_app_event_relationships               | relationships       | CREATE TRIGGER log_app_event_relationships AFTER INSERT OR DELETE OR UPDATE ON public.relationships FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                     |
| log_app_event_texts                       | texts               | CREATE TRIGGER log_app_event_texts AFTER INSERT OR DELETE OR UPDATE ON public.texts FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                                     |
| log_app_event_comms                       | comms               | CREATE TRIGGER log_app_event_comms AFTER INSERT OR DELETE OR UPDATE ON public.comms FOR EACH ROW EXECUTE FUNCTION log_all_events()                                                                                     |
| new_survey_create_default_question_answer | survey_headers      | CREATE TRIGGER new_survey_create_default_question_answer AFTER INSERT ON public.survey_headers FOR EACH ROW EXECUTE FUNCTION "new_survey_header_create_Q1_A1"()                                                        |
| new_survey_create_appro                   | survey_headers      | CREATE TRIGGER new_survey_create_appro AFTER INSERT ON public.survey_headers FOR EACH ROW EXECUTE FUNCTION new_survey_headers_create_appro()                                                                           |